In [4]:
import numpy as np
import pandas as pd
import random

In [5]:
import gym
env = gym.make('CartPole-v0')

In [6]:
env.seed(100) 
env.action_space.seed(100)
random.seed(100)
np.random.seed(100)

In [24]:
def run_one_episode(env):
  state = env.reset()
  for step in range(200):
    a = random.randint(0,1)
    state, reward, done, info = env.step(a)
    if done:
      break
    print(state, reward, info)
  return step

In [25]:
nosteps = run_one_episode(env)
if nosteps >= 200:
  print(f'SUCCESS')
else:
  print(f'FAIL')
print(f'nosteps = {nosteps}')

[ 0.02010193 -0.23786442 -0.0182998   0.24779174] 1.0 {}
[ 0.01534464 -0.04248597 -0.01334396 -0.05060671] 1.0 {}
[ 0.01449492 -0.23741406 -0.01435609  0.23783639] 1.0 {}
[ 0.00974664 -0.04208999 -0.00959937 -0.05934007] 1.0 {}
[ 0.00890484 -0.237073   -0.01078617  0.2302988 ] 1.0 {}
[ 0.00416338 -0.43203917 -0.00618019  0.51956   ] 1.0 {}
[-0.0044774  -0.23683076  0.00421101  0.224936  ] 1.0 {}
[-0.00921401 -0.04176925  0.00870973 -0.06641566] 1.0 {}
[-0.0100494  -0.23701498  0.00738141  0.22900246] 1.0 {}
[-0.0147897  -0.43224162  0.01196146  0.5240046 ] 1.0 {}
[-0.02343453 -0.23729004  0.02244155  0.23511471] 1.0 {}
[-0.02818033 -0.4327253   0.02714385  0.53479105] 1.0 {}
[-0.03683484 -0.23799539  0.03783967  0.2507831 ] 1.0 {}
[-0.04159475 -0.04343365  0.04285533 -0.02972842] 1.0 {}
[-0.04246342 -0.23914313  0.04226076  0.27616188] 1.0 {}
[-0.04724628 -0.0446488   0.047784   -0.00289816] 1.0 {}
[-0.04813926  0.14975645  0.04772604 -0.28013003] 1.0 {}
[-0.04514413 -0.04601267  0.042